
// This file is automatically generated. Do not edit it directly.
import { supabase } from '@/lib/supabase';
import type { Database } from '../integrations/supabase/types';

// Export the isUserPartner function for use in the UserDropdownContent component
export const isUserPartner = async (userId: string): Promise<boolean> => {
  if (!userId) return false;
  
  try {
    const { data, error } = await supabase
      .from('partners')
      .select('id')
      .eq('user_id', userId)
      .single();
  
    if (error && error.code !== 'PGRST116') { // PGRST116 is the error for "no rows returned"
      console.error('Error checking if user is partner:', error);
      throw error;
    }
  
    return !!data;
  } catch (error) {
    console.error('Error checking if user is partner:', error);
    return false;
  }
};
