
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xsctqejremuwmktmchef.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhzY3RxZWpyZW11d21rdG1jaGVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2NzEzMDEsImV4cCI6MjA1OTI0NzMwMX0.2IaG53q-EuHkupqC3qvOSSzf7wMVPKpYWoJsLt0susU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
